# Generated by Django 4.1.4 on 2022-12-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollaborationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Type Collaboration",
                "verbose_name_plural": "Type Collaborations",
                "db_table": "Collaboration-type",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attached", models.BooleanField()),
                (
                    "condition",
                    models.CharField(
                        blank=True, db_column="Condition", max_length=255, null=True
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Condition",
                "verbose_name_plural": "Conditions",
                "db_table": "Condition",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom"
                    ),
                ),
                ("discriminator", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "db_table": "country",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DefaultAidType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Type aide",
                "verbose_name_plural": "Type aides",
                "db_table": "default-aid-type",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DefaultFinanceType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Type Financement",
                "verbose_name_plural": "Type Financements",
                "db_table": "Default-finance-type",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HumanitarianScope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Portée humanitaire",
                "verbose_name_plural": "Portée humanitaires",
                "db_table": "Humanitarian-scope",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("narrative", models.CharField(blank=True, max_length=255, null=True)),
                ("discriminator", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "db_table": "organization",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("continent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom"
                    ),
                ),
                ("discriminator", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Région",
                "verbose_name_plural": "Régions",
                "db_table": "region",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("percentage", models.FloatField(verbose_name="Pourcentage")),
                ("narrative", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Secteur",
                "verbose_name_plural": "Secteurs",
                "db_table": "sector",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("narrative", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Etiquette",
                "verbose_name_plural": "Etiquettes",
                "db_table": "Tag",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Réference"
                    ),
                ),
                (
                    "location_reach",
                    models.CharField(
                        blank=True,
                        db_column="Location-reach",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "activity_location",
                    models.CharField(
                        blank=True,
                        db_column="Activity-location",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "administrative_code",
                    models.IntegerField(
                        blank=True, db_column="Administrative-code", null=True
                    ),
                ),
                (
                    "administrative_level",
                    models.CharField(
                        blank=True,
                        db_column="Administrative-level",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("pos", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "location_class",
                    models.CharField(
                        blank=True,
                        db_column="Location-class",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "countryid3",
                    models.ForeignKey(
                        db_column="countryid3",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iati_referentiel.country",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localité",
                "verbose_name_plural": "Localités",
                "db_table": "location",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="country",
            name="regionid",
            field=models.ForeignKey(
                db_column="regionid",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iati_referentiel.region",
                verbose_name="Région",
            ),
        ),
    ]
