# Generated by Django 3.1.13 on 2022-12-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Collaboration-type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('discriminator', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultAidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'default-aid-type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultFinanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Default-finance-type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HumanitarianScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Humanitarian-scope',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('location_reach', models.CharField(blank=True, db_column='Location-reach', max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_location', models.CharField(blank=True, db_column='Activity-location', max_length=255, null=True)),
                ('administrative_code', models.IntegerField(blank=True, db_column='Administrative-code', null=True)),
                ('administrative_level', models.CharField(blank=True, db_column='Administrative-level', max_length=255, null=True)),
                ('pos', models.CharField(blank=True, max_length=255, null=True)),
                ('location_class', models.CharField(blank=True, db_column='Location-class', max_length=255, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('narrative', models.CharField(blank=True, max_length=255, null=True)),
                ('discriminator', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('discriminator', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage', models.FloatField()),
                ('narrative', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
    ]
