# Generated by Django 3.1.13 on 2022-12-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationtype',
            options={'managed': False, 'verbose_name': 'Type Collaboration', 'verbose_name_plural': 'Type Collaborations'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False, 'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.AlterModelOptions(
            name='defaultaidtype',
            options={'managed': False, 'verbose_name': "Type d'aide", 'verbose_name_plural': "Type d'aides"},
        ),
        migrations.AlterModelOptions(
            name='defaultfinancetype',
            options={'managed': False, 'verbose_name': 'Type Financement', 'verbose_name_plural': 'Type Financements'},
        ),
        migrations.AlterModelOptions(
            name='humanitarianscope',
            options={'managed': False, 'verbose_name': 'Portée humanitaire', 'verbose_name_plural': 'Portée humanitaires'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False, 'verbose_name': 'Localité', 'verbose_name_plural': 'Localités'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': False, 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False, 'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'managed': False, 'verbose_name': 'Secteur', 'verbose_name_plural': 'Secteurs'},
        ),
    ]
