# Generated by Django 3.1.13 on 2022-12-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_referentiel', '0002_auto_20221207_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached', models.BooleanField()),
                ('condition', models.CharField(blank=True, db_column='Condition', max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Conditions',
                'db_table': 'Condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('narrative', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Etiquette',
                'verbose_name_plural': 'Etiquettes',
                'db_table': 'Tag',
                'managed': False,
            },
        ),
    ]
