# Generated by Django 4.1.4 on 2022-12-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iati_activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitytag",
            options={
                "managed": False,
                "verbose_name": "Etiquette Projet",
                "verbose_name_plural": "Etiquette Projet",
            },
        ),
        migrations.AlterModelOptions(
            name="budget",
            options={
                "managed": False,
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
            },
        ),
        migrations.AlterModelOptions(
            name="conditionactivity",
            options={
                "managed": False,
                "verbose_name": "Condition",
                "verbose_name_plural": "Conditions",
            },
        ),
        migrations.AlterModelOptions(
            name="defaultaidtypeactivity",
            options={
                "managed": False,
                "verbose_name": "Type Aide Par Defaut",
                "verbose_name_plural": "Type Aide Par Defaut",
            },
        ),
        migrations.AlterModelOptions(
            name="results",
            options={
                "managed": False,
                "verbose_name": "Resultat",
                "verbose_name_plural": "Resultats",
            },
        ),
    ]
