# Generated by Django 4.1.4 on 2022-12-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "iati_activities",
            "0002_alter_activitytag_options_alter_budget_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "managed": False,
                "verbose_name": "Activitée",
                "verbose_name_plural": "Activitées",
            },
        ),
        migrations.AlterModelOptions(
            name="activitycollaborationtype",
            options={
                "managed": False,
                "verbose_name": "Collaboration Activité",
                "verbose_name_plural": "Collaboration Activité",
            },
        ),
        migrations.AlterModelOptions(
            name="activitydate",
            options={
                "managed": False,
                "verbose_name": "Date Activitée",
                "verbose_name_plural": "Date Activitée",
            },
        ),
        migrations.AlterModelOptions(
            name="actual",
            options={"managed": False, "verbose_name": "Réel"},
        ),
        migrations.AlterModelOptions(
            name="actualdimension",
            options={"managed": False, "verbose_name": "Dimension Réel"},
        ),
        migrations.AlterModelOptions(
            name="actualdocumentlink",
            options={
                "managed": False,
                "verbose_name": "Document Réel",
                "verbose_name_plural": "Documents Réel",
            },
        ),
        migrations.AlterModelOptions(
            name="baseline",
            options={"managed": False, "verbose_name": "Ligne de Base"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"managed": False, "verbose_name": "Commentaire"},
        ),
        migrations.AlterModelOptions(
            name="indicator",
            options={"managed": False, "verbose_name": "Indicateur"},
        ),
        migrations.AlterModelOptions(
            name="period",
            options={"managed": False, "verbose_name": "Periode"},
        ),
        migrations.AlterModelOptions(
            name="planneddisbursement",
            options={
                "managed": False,
                "verbose_name": "Plan de distribution",
                "verbose_name_plural": "Plan de distribution",
            },
        ),
        migrations.AlterModelOptions(
            name="target",
            options={"managed": False, "verbose_name": "Jalon"},
        ),
        migrations.AlterModelOptions(
            name="targetcomment2",
            options={"managed": False, "verbose_name": "Commentaire Jalon"},
        ),
        migrations.AlterModelOptions(
            name="targetdimension",
            options={"managed": False, "verbose_name": "Dimension Jalon"},
        ),
        migrations.AlterModelOptions(
            name="transactionsector",
            options={
                "managed": False,
                "verbose_name": "Secteur Transaction",
                "verbose_name_plural": "Secteur Transaction",
            },
        ),
    ]
