# Generated by Django 3.2 on 2021-04-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taux', models.PositiveSmallIntegerField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activite.activites')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activite.programmephysique')),
            ],
        ),
    ]
