# Generated by Django 3.2 on 2021-04-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0002_alter_taux_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='trimestre',
            field=models.CharField(max_length=40),
        ),
    ]
