# Generated by Django 3.2 on 2021-04-17 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0002_alter_programmephysique_id'),
        ('rapport', '0003_alter_taux_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='trimestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activite.programmephysique'),
        ),
    ]
