# Generated by Django 3.2 on 2021-05-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generiquemodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('devise', models.CharField(max_length=255, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=255, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammePhysique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trimestre', models.CharField(max_length=255, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Programmations Physique',
            },
        ),
        migrations.CreateModel(
            name='SourceFinancement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StructureResponsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField(unique=True)),
                ('intitule', models.CharField(max_length=1000)),
                ('resultat_attendu', models.CharField(max_length=1000)),
                ('indicateur', models.CharField(max_length=255)),
                ('cible', models.PositiveIntegerField()),
                ('cout', models.PositiveBigIntegerField()),
                ('resultat_atteints', models.TextField(blank=True, null=True)),
                ('taux_execution', models.IntegerField(blank=True, default=0, null=True)),
                ('cout_effective', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activite.devise')),
                ('etiquette', models.ManyToManyField(blank=True, to='activite.Etiquette')),
                ('financement', models.ManyToManyField(to='activite.SourceFinancement')),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generiquemodel.generictable')),
                ('pogrammation', models.ManyToManyField(to='activite.ProgrammePhysique')),
                ('structure', models.ManyToManyField(to='activite.StructureResponsable')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
    ]
