# Generated by Django 3.2 on 2021-04-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0002_alter_programmephysique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activites',
            options={'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AlterModelOptions(
            name='programmephysique',
            options={'verbose_name': 'Programmations Physique'},
        ),
        migrations.AddField(
            model_name='activites',
            name='cout_effective',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='activites',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activites',
            name='resultat_atteints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activites',
            name='taux_execution',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='programmephysique',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
