# Generated by Django 3.2 on 2021-05-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.PositiveSmallIntegerField(unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Année',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=255, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('budjet', models.PositiveBigIntegerField(blank=True, default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=255)),
                ('code', models.PositiveIntegerField(unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('annee', models.ManyToManyField(to='generiquemodel.Annee')),
                ('element_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generiquemodel.generictable')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generiquemodel.niveau')),
                ('structure', models.ManyToManyField(to='generiquemodel.Structure')),
            ],
        ),
    ]
