# Generated by Django 3.2 on 2021-04-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generiquemodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annee',
            options={'verbose_name': 'Année'},
        ),
    ]
